# Generated by Django 2.1.3 on 2019-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='descriptipn',
            field=models.TextField(),
        ),
    ]
