# Generated by Django 2.1.4 on 2019-02-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='js_file',
            new_name='game_file',
        ),
    ]
