# Generated by Django 2.1.4 on 2019-02-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190201_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(upload_to='uploads/gamefiles/'),
        ),
    ]
