# Generated by Django 2.1.4 on 2019-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190201_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=150)),
                ('gameState', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='Rank1player',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='Rank1pts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='Rank2player',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='Rank2pts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='Rank3player',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='Rank3pts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='URL',
            field=models.URLField(default=None),
        ),
    ]
