# Generated by Django 2.1.4 on 2019-02-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190209_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='URL',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
