# Generated by Django 2.1.4 on 2019-02-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190209_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='URL',
        ),
    ]
