# Generated by Django 2.1.4 on 2019-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='URL',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
