# Generated by Django 2.1.4 on 2019-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='URL',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
