# Generated by Django 2.1.4 on 2019-02-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190209_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
