# Generated by Django 2.1.4 on 2019-02-14 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20190209_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='save',
            options={},
        ),
        migrations.RemoveField(
            model_name='save',
            name='title',
        ),
        migrations.AddField(
            model_name='save',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Game'),
        ),
        migrations.AlterField(
            model_name='save',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
