# Generated by Django 2.1.4 on 2019-02-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20190215_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.AddField(
            model_name='save',
            name='name',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
    ]
