# Generated by Django 2.1.4 on 2019-02-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20190215_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='name',
            new_name='username',
        ),
    ]
