# Generated by Django 2.1.4 on 2019-02-15 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_auto_20190215_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='save',
            name='username',
        ),
        migrations.AddField(
            model_name='highscore',
            name='username',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
