# Generated by Django 2.1.5 on 2019-01-13 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('checksum', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('CANCEL', 'Cancel'), ('ERROR', 'Error')], default='PENDING', max_length=7)),
            ],
        ),
    ]
