# Generated by Django 2.1.4 on 2019-02-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190201_0445'),
        ('payment', '0004_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Game'),
        ),
    ]
